name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:  # Enable manual triggering

jobs:
  push_to_registry:
    name: anshusharma17
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: anshusharma17
          password: dckr_pat_2k-ZHPSUAmWSmAr_T5JEd2UPaAI  # Use your Docker Hub token stored as a secret
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: anshusharma17/react-template-demo-1
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
